package exceptionhandling;


public class Demo {

	public static void main(String[] args) {
		   
		   
		 int n1=10;
		 int n2=0;
		 
		 try {
		      int n =  n1/n2;
		 }
		 catch(Exception e)
		 {
			System.out.println("hi"); 
		 }

	}

}
